#!/bin/bash
echo "__name__: ${BASH_SOURCE[0]}"

kernel_versions="5.4.0-1015-raspi 5.4.0-1022-raspi"
curr_kernel_version=$(uname -r)

eval "set -- ${kernel_versions}"

hunt=0
for v in ${kernel_versions}; do
  if [ "${curr_kernel_version}" == "$v" ] ; then
    hunt=1
  fi
#  ret=$(dpkg -l linux-image-${v} > /dev/null 2>&1; echo $?;)
#  [ $ret -eq 0 ] && echo $v=yes || echo $v=no ;
done

if [ $hunt -ne 1 ] ; then
  exit 1; 
fi

