#!/bin/bash
echo "__name__: ${BASH_SOURCE[0]}"
# depmod -b / __kernel_version__ -A -a 
if [ -z $RUNLEVL ] || [ $RUNLEVEL -ne 1 ] ; then
  depmod -a
else
#  depmod -b / $(uname -r) -A -a 
  depmod -b / __kernel_version__ -A -a 
fi
